export default {
    KEY_USER_ID: 'user_id',
    KEY_ACCESS_TOKEN: 'access_token',
    KEY_USER_PROFILE: 'user_profile',
    KEY_DIVISION: 'division',
    KEY_FIREBASE_TOKEN: 'firebase_token',
    KEY_SETTINGS: 'settings',
    KEY_PROVINCE: 'province',
    KEY_COMPANY: 'company',
    KEY_GENDER: 'gender',
    KEY_BANK: 'bank',
    KEY_VEHICLE_OWNERSHIP: 'vehicle_ownership',
    KEY_VEHICLE_STICKER: 'vehicle_sticker',
    KEY_VEHICLE_USAGE: 'vehicle_usage',
    KEY_VEHICLE_TYPE: 'vehicle_type',
    KEY_COLOR: 'color',
    KEY_DO_JOB: 'do_job',
    KEY_ACTIVE_CONTRACT: 'active_contract',
    KEY_BACKGROUND_ACTIVE: 'background_active',
    KEY_START_TIME: 'start_time'
}