fastlane_version '2.53.1'

ios_version = "1.3.2"
android_version = '1.3.2'

# before_all do
#   ensure_git_branch
#   ensure_git_status_clean
#   git_pull
# end

platform :ios do
   # iOS Lanes
    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
        match(app_identifier: 'com.schott.pbsaving.ios', type: 'development', readonly: false)
        match(app_identifier: 'com.schott.pbsaving.ios', type: 'appstore', readonly: false)
    end

    desc 'Build the iOS application.'
    private_lane :build do
        certificates
        # increment_version_number(version_number: ios_version, xcodeproj: './ios/PBSaving.xcodeproj' # Set a specific version number)
        increment_build_number(xcodeproj: './ios/PBSaving.xcodeproj')
        gym(scheme: 'PBSaving', workspace: './ios/PBSaving.xcworkspace')
    end

    desc 'Ship to Testflight.'
    lane :beta do
        build
        pilot
        commit_version_bump(message: 'Bump build', xcodeproj: './ios/PBSaving.xcodeproj')
        push_to_git_remote
  end
end

platform :android do
  # Android Lanes
    desc 'Build the Android application.'
    private_lane :build do
        android_set_version_name(
            version_name: android_version,
            gradle_file: "./android/app/build.gradle" # optional
          )
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/', properties: {
            "android.injected.signing.store.file" => "keystore.jks",
            "android.injected.signing.store.password" => "timedoor123",
            "android.injected.signing.key.alias" => "key0",
            "android.injected.signing.key.password" => "timedoor123",
          })
    end

    desc 'Ship to Playstore Beta.'
    lane :beta do
        build
        supply(track: 'beta', track_promote_to: 'beta')
        git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
        push_to_git_remote
    end
end
